export const assetsToLoad = {
    'champ_okomo': 'images/Characters/Champions/Okomo.png',
    'demon': 'images/Characters/Monsters/Demons/ArmouredRedDemon.png',
    'flame_guardian': 'images/Characters/Monsters/Demons/RedDemon.png',
    'imp': 'images/Characters/Monsters/Demons/PurpleDemon.png',
    'black_dragon': 'images/Characters/Monsters/Dragons/BlackDragon.png',
    'blue_dragon': 'images/Characters/Monsters/Dragons/BlueDragon.png',
    'red_dragon': 'images/Characters/Monsters/Dragons/RedDragon.png',
    'white_dragon': 'images/Characters/Monsters/Dragons/WhiteDragon.png',
    'yellow_dragon': 'images/Characters/Monsters/Dragons/YellowDragon.png',
    'giant_crab': 'images/Characters/Monsters/GiantAnimals/GiantCrab.png',
    'mammoth': 'images/Characters/Monsters/Frostborn/Mammoth.png',
    'wendigo': 'images/Characters/Monsters/Frostborn/Wendigo.png',
    'yeti': 'images/Characters/Monsters/Frostborn/Yeti.png',
    'archer_goblin': 'images/Characters/Monsters/Orcs/ArcherGoblin.png',
    'club_goblin': 'images/Characters/Monsters/Orcs/ClubGoblin.png',
    'farmer_goblin': 'images/Characters/Monsters/Orcs/FarmerGoblin.png',
    'kamikaze_goblin': 'images/Characters/Monsters/Orcs/KamikazeGoblin.png',
    'minotaur': 'images/Characters/Monsters/Orcs/Minotaur.png',
    'orc': 'images/Characters/Monsters/Orcs/Orc.png',
    'orc_mage': 'images/Characters/Monsters/Orcs/OrcMage.png',
    'orc_shaman': 'images/Characters/Monsters/Orcs/OrcShaman.png',
    'spear_goblin': 'images/Characters/Monsters/Orcs/SpearGoblin.png',
    'pirate_captain': 'images/Characters/Monsters/Pirates/PirateCaptain.png',
    'pirate_grunt': 'images/Characters/Monsters/Pirates/PirateGrunt.png',
    'pirate_gunner': 'images/Characters/Monsters/Pirates/PirateGunner.png',
    'blue_slime': 'images/Characters/Monsters/Slimes/SlimeBlue.png',
    'green_slime': 'images/Characters/Monsters/Slimes/Slime.png',
    'king_blue_slime': 'images/Characters/Monsters/Slimes/KingSlimeBlue.png',
    'king_green_slime': 'images/Characters/Monsters/Slimes/KingSlimeGreen.png',
    'mega_blue_slime': 'images/Characters/Monsters/Slimes/MegaSlimeBlue.png',
    'mega_green_slime': 'images/Characters/Monsters/Slimes/MegaSlimeGreen.png',
    'necromancer': 'images/Characters/Monsters/Undead/Necromancer.png',
    'skeleton': 'images/Characters/Monsters/Undead/Skeleton-Soldier.png',
    'peasant': 'images/Characters/Workers/CyanWorker/FarmerCyan.png',
    'potion_health': 'images/Objects/potions.png',
    'terrain': './images/Ground/Grass.png',
    'town': './images/Buildings/Wood/Keep.png',
    'pine_tree': './images/Nature/Trees.png',
    'tree': './images/Nature/Trees.png',
    'stump_tree': './images/Nature/Trees.png',
    'wood': './images/Nature/PineTrees.png',
    'stone': './images/Nature/Rocks.png',
    'gold': './images/Nature/PineTrees.png',
    'road': './images/Ground/road.png',
    'water_bg_1': './images/backgrounds/water.png',
    'water_bg_2': './images/backgrounds/water.png',
    'sand_bg_1': './images/backgrounds/beach.png',
    'sand_bg_2': './images/backgrounds/beach2.png',
    'grass_bg_1': './images/backgrounds/grass.png',
    'grass_bg_2': './images/backgrounds/grass2.png',
    'forest_bg_1': './images/backgrounds/forest.png',
    'forest_bg_2': './images/backgrounds/forest2.png',
    'mountain_bg_1': './images/backgrounds/mountain.png',
    'mountain_bg_2': './images/backgrounds/mountain2.png',
    'overworld_ocean0': './images/tiles_overworld/ocean/0.png',
    'overworld_river0': './images/tiles_overworld/river/0.png',
    'overworld_coast0': './images/tiles_overworld/coast/0.png',
    'overworld_desert0': './images/tiles_overworld/desert/0.png',
    'overworld_grass0': './images/tiles_overworld/grass/0.png',
    'overworld_forest0': './images/tiles_overworld/forest/0.png',
    'overworld_mountain0': './images/tiles_overworld/mountain/0.png',
    'overworld_volcanic0': './images/tiles_overworld/volcanic/0.png',
    'overworld_mystical0': './images/tiles_overworld/mystical/0.png',
    'overworld_ruins0': './images/tiles_overworld/ruins/0.png',
  //  'overworld_coast1': './images/tiles_overworld/coast/1.png',
  //  'overworld_coast2': './images/tiles_overworld/coast/2.png',
  //  'overworld_coast3': './images/tiles_overworld/coast/3.png',
  //  'overworld_coast0_1': './images/tiles_overworld/coast/0_1.png',
  //  'overworld_coast0_2': './images/tiles_overworld/coast/0_2.png',
  //   'overworld_desert1': './images/tiles_overworld/desert/1.png',
  //   'overworld_desert2': './images/tiles_overworld/desert/2.png',
  //   'overworld_desert3': './images/tiles_overworld/desert/3.png',
  //   'overworld_desert0_1': './images/tiles_overworld/desert/0_1.png',
  //   'overworld_desert0_2': './images/tiles_overworld/desert/0_2.png',
  //   'overworld_grass0_1': './images/tiles_overworld/grass/0_1.png',
  //   'overworld_grass0_2': './images/tiles_overworld/grass/0_2.png',
  //   'overworld_grass1': './images/tiles_overworld/grass/1.png',
  //   'overworld_grass2': './images/tiles_overworld/grass/2.png',
  //   'overworld_grass3': './images/tiles_overworld/grass/3.png',
  //   'overworld_forest1': './images/tiles_overworld/forest/1.png',
  //   'overworld_forest2': './images/tiles_overworld/forest/2.png',
  //   'overworld_forest3': './images/tiles_overworld/forest/3.png',
  //   'overworld_forest0_1': './images/tiles_overworld/forest/0_1.png',
  //   'overworld_forest0_2': './images/tiles_overworld/forest/0_2.png',
  //   'overworld_mountain1': './images/tiles_overworld/mountain/1.png',
  //   'overworld_mountain2': './images/tiles_overworld/mountain/2.png',
  //   'overworld_mountain3': './images/tiles_overworld/mountain/3.png',
  //   'overworld_volcanic1': './images/tiles_overworld/volcanic/1.png',
  //   'overworld_volcanic2': './images/tiles_overworld/volcanic/2.png',
  //   'overworld_volcanic3': './images/tiles_overworld/volcanic/3.png',
    'terrain_water0': './images/tiles_terrain/water/0.png',
    'terrain_sand0': './images/tiles_terrain/sand/0.png',
    'terrain_sand1': './images/tiles_terrain/sand/1.png',
    'terrain_sand2': './images/tiles_terrain/sand/2.png',
    'terrain_sand3': './images/tiles_terrain/sand/3.png',
    'terrain_sand0_1': './images/tiles_terrain/sand/0_1.png',
    'terrain_sand0_2': './images/tiles_terrain/sand/0_2.png',
    'terrain_grass0_1': './images/tiles_terrain/grass/0_1.png',
    'terrain_grass0_2': './images/tiles_terrain/grass/0_2.png',
    'terrain_grass0': './images/tiles_terrain/grass/0.png',
    'terrain_grass1': './images/tiles_terrain/grass/1.png',
    'terrain_grass2': './images/tiles_terrain/grass/2.png',
    'terrain_grass3': './images/tiles_terrain/grass/3.png',
    'terrain_forest0': './images/tiles_terrain/forest/0.png',
    'terrain_forest1': './images/tiles_terrain/forest/1.png',
    'terrain_forest2': './images/tiles_terrain/forest/2.png',
    'terrain_forest3': './images/tiles_terrain/forest/3.png',
    'terrain_forest0_1': './images/tiles_terrain/forest/0_1.png',
    'terrain_forest0_2': './images/tiles_terrain/forest/0_2.png',
    'terrain_mountain0': './images/tiles_terrain/mountain/0.png',
    'terrain_mountain1': './images/tiles_terrain/mountain/1.png',
    'terrain_mountain2': './images/tiles_terrain/mountain/2.png',
    'terrain_mountain3': './images/tiles_terrain/mountain/3.png',
    'terrain_road0': './images/tiles_terrain/road/0.png',
    'box_selector': './images/ui/BoxSelector.png',
    'house': './images/Buildings/Wood/huts.png',
    'blacksmith': './images/Buildings/Wood/Workshops.png',
    'barracks': './images/Buildings/Wood/Barracks.png',
    'market': './images/Buildings/Wood/Market.png',
    'tavern': './images/Buildings/Wood/Taverns.png',
    'temple': './images/Buildings/Wood/Chapels.png',
    'dock': './images/Buildings/Wood/Docks.png',
    'wood_barricade': './images/Buildings/Wood/Tower.png',
    'stone_wall': './images/Buildings/Wood/Tower.png',
    'arrow_tower': './images/Buildings/Wood/Tower.png',
    'blacksmith_bg_1': './images/backgrounds/blacksmith.png',
    'blacksmith_bg_2': './images/backgrounds/blacksmith.png',
    'barracks_bg_1': './images/backgrounds/barracks.png',
    'barracks_bg_2': './images/backgrounds/barracks.png',
    'market_bg_1': './images/backgrounds/market.png',
    'market_bg_2': './images/backgrounds/market.png',
    'tavern_bg_1': './images/backgrounds/tavern.png',
    'tavern_bg_2': './images/backgrounds/tavern2.png',
    'temple_bg_1': './images/backgrounds/temple.png',
    'temple_bg_2': './images/backgrounds/temple.png',
    'dock_bg_1': './images/backgrounds/dock.png',
    'dock_bg_2': './images/backgrounds/dock.png',
    'road_bg_1': './images/backgrounds/road.png',
    'ramp': './images/Ground/ramp.png',
    'resource_wood': './images/ui/wood.png',
    'resource_stone': './images/ui/stone.png'
  };

